# Generated by Django 3.2.5 on 2021-07-20 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name="User's first name")),
                ('last_name', models.CharField(max_length=150, verbose_name="User's first name")),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{4}$')])),
            ],
        ),
    ]
